### ISSUE TITLE
Database schema planning

### ISSUE THREAD

**Issue by tmikeschu** [tmikeschu/mogo-reporter#3]
|Record|Attributes|---|---|---|
|---|---|---|---|---|
|Users| first_name | last_name | email | phone_number | password |
|IncidentPins| lat | lng | description | etc |
|MogoLocations| lat | lng | title | |etc|

http://ondras.zarovi.cz/sql/demo/

**Comment by gl2748** [comment]
Not fully aware of what information the client wants recorded in a report. the 'nearlykilled.me' report is fairly detailed: https://nearlykilled.me/ perhaps because they use this info to advocate for changes , i have no idea...

I would suggest boiling this down to two or three questions for the purposes of the prototype and ideally in a fully fledged app we would give simplicity primacy with as much data extrapolated from user metadata...

# user input data.
### - Hazard type.
  - :car: car 
  - :vertical_traffic_light: road 
  - :construction: obstacle


### - Danger level
   - :rage4:  Persistent hazard that demands immediate attention. e.g. gaping pothole. 
   - :rage: Near miss with  hazard having passed. e.g. being cut off by a moving vehicle.
   - :angry: Peeved, lack of courtesy, road rage. e.g. aggressive driver toots their horn.

Having a simple questionnaire like this would allow users to quikly(sic) orientate themselves in the event of a 'mogo no no' (tm) and then get on with their busy lives.

# inferred data.

- location (app must record user data.)
- time (contemporaneous reporting only)
- name, email, phone etc... (authenticated users only)

# precedent (the nearly killed me mind fudger)

![screenshot from 2017-12-16 18-42-49](https://user-images.githubusercontent.com/3374538/34075315-1a302ec0-e291-11e7-8952-48391bc6d01d.png)

**Comment by tmikeschu** [comment]
Closed by #22
